# Generated by Django 5.0.4 on 2024-05-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceldata',
            name='column1',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='column2',
        ),
        migrations.AddField(
            model_name='exceldata',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
