# Generated by Django 5.0.4 on 2024-05-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_exceldata_column1_remove_exceldata_column2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='data',
            field=models.JSONField(),
        ),
    ]
