# Generated by Django 5.0.4 on 2024-05-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_exceldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCase',
        ),
    ]
