# Generated by Django 5.0.4 on 2024-05-25 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_delete_testcase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelData',
        ),
    ]
