# Generated by Django 5.0.4 on 2024-07-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_formdetail_delete_userdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormDetail',
        ),
    ]
