# Generated by Django 5.0.4 on 2024-07-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_formdata_doors_test_spec_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='doors_document',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='test_description_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
