# Generated by Django 5.0.4 on 2024-07-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_rename_doors_document_formdata_input1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCase',
        ),
    ]
